language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  include:
    - php: 5.6
      evn: NETTE_VERSION=2.1.*
    - php: 5.6
      evn: NETTE_VERSION=2.2.*
  allow_failures:
    - php: 7.0
    - php: hhvm

install:
  - sh -c 'if [ "$NETTE_VERSION" != "" ]; then composer require --no-update nette/nette=$NETTE_VERSION; fi;'
  - composer install --prefer-source

script:
  - phpunit
